"""Animated bilingual caption generation (ASS/SSA, rendered by libass).

Each script line becomes two events: the primary-language line (lower,
larger) and the support-language line right beneath it. Animation styles:
``fade`` (default), ``pop`` (scale-in), ``slide`` (move-up), or ``none``.
Optionally the primary line gets karaoke word highlighting when the
alignment carried word timings.
"""

from __future__ import annotations

from dataclasses import dataclass

from openclip.engine.align import Alignment, LineAlignment
from openclip.engine.jsonio import as_int

ANIMATIONS = ("fade", "pop", "slide", "none")


@dataclass
class CaptionStyle:
    primary_font: str = "Arial"
    primary_size: int = 28
    support_font: str = "Arial"
    support_size: int = 20
    animation: str = "fade"
    karaoke: bool = False
    margin_v: int = 60
    support_margin_v: int = 110
    primary_color: str = "&H00FFFFFF"
    support_color: str = "&H00D0D8E8"
    outline: int = 2

    def to_dict(self) -> dict[str, object]:
        return {
            "primary_font": self.primary_font,
            "primary_size": self.primary_size,
            "support_font": self.support_font,
            "support_size": self.support_size,
            "animation": self.animation,
            "karaoke": self.karaoke,
            "margin_v": self.margin_v,
            "support_margin_v": self.support_margin_v,
            "primary_color": self.primary_color,
            "support_color": self.support_color,
            "outline": self.outline,
        }

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> CaptionStyle:
        from openclip.engine.jsonio import as_bool, as_int, as_str

        return cls(
            primary_font=as_str(data, "primary_font", "Arial"),
            primary_size=as_int(data, "primary_size", 28),
            support_font=as_str(data, "support_font", "Arial"),
            support_size=as_int(data, "support_size", 20),
            animation=as_str(data, "animation", "fade"),
            karaoke=as_bool(data, "karaoke", False),
            margin_v=as_int(data, "margin_v", 60),
            support_margin_v=as_int(data, "support_margin_v", 110),
            primary_color=as_str(data, "primary_color", "&H00FFFFFF"),
            support_color=as_str(data, "support_color", "&H00D0D8E8"),
            outline=as_int(data, "outline", 2),
        )


def _ts(seconds: float) -> str:
    """Format seconds as ASS timestamp H:MM:SS.cc (centisecond precision)."""
    cs = round(max(0.0, seconds) * 100.0)
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    sec, c = divmod(rem, 100)
    return f"{h}:{m:02d}:{sec:02d}.{c:02d}"


def _animation_tag(style: CaptionStyle, res_x: int, res_y: int, bottom_margin: int) -> str:
    a = style.animation
    if a == "fade":
        return r"{\fad(160,160)}"
    if a == "pop":
        return r"{\fscx70\fscy70\t(0,140,\fscx100\fscy100)\fad(60,120)}"
    if a == "slide":
        x = res_x // 2
        y1 = res_y - bottom_margin + 26
        y2 = res_y - bottom_margin
        return rf"{{\move({x},{y1},{x},{y2},0,160)\fad(80,120)}}"
    return ""


def _karaoke_text(line: LineAlignment) -> str:
    words = line.matched_words
    if not words:
        return ""
    per_word = max(
        4, int((line.end_s - line.start_s) * 100.0 / len(words))
    )
    parts = []
    for w in words:
        w_clean = w.replace("{", "(").replace("}", ")")
        parts.append(rf"{{\k{per_word}}}{w_clean}")
    return "".join(parts)


def build_ass(
    script_lines: list[dict[str, object]],
    alignment: Alignment,
    res_x: int,
    res_y: int,
    style: CaptionStyle,
) -> str:
    """Build a complete ASS document with events in *final-timeline* times.

    Callers must map source-timeline alignment into the export timeline
    (post-cut) before calling this; see ``openclip.engine.render``.
    """
    style.animation = style.animation if style.animation in ANIMATIONS else "fade"
    head = [
        "[Script Info]",
        "; Generated by Eterna OpenClip Studio",
        "ScriptType: v4.00+",
        "WrapStyle: 2",
        f"PlayResX: {res_x}",
        f"PlayResY: {res_y}",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Primary,{style.primary_font},{style.primary_size},"
        f"{style.primary_color},&H000000FF,&H00101010,&H80000000,"
        f"0,0,0,0,100,100,0,0,1,{style.outline},1,2,40,40,{style.margin_v},1",
        f"Style: Support,{style.support_font},{style.support_size},"
        f"{style.support_color},&H000000FF,&H00101010,&H80000000,"
        f"0,0,0,0,100,100,0,0,1,{style.outline},1,2,40,40,{style.support_margin_v},1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    by_index = {ln.index: ln for ln in alignment.lines}
    events: list[str] = []
    for entry in script_lines:
        idx = as_int(entry, "index", -1)
        line = by_index.get(idx)
        if line is None or line.confidence <= 0.0 or line.end_s <= line.start_s:
            continue
        start, end = _ts(line.start_s), _ts(line.end_s + 0.05)
        primary_text = str(entry.get("primary", ""))
        support_text = str(entry.get("support", ""))
        if style.karaoke:
            k = _karaoke_text(line)
            if k:
                primary_text = k
        tag_primary = _animation_tag(style, res_x, res_y, style.margin_v)
        tag_support = _animation_tag(style, res_x, res_y, style.support_margin_v)
        safe_primary = primary_text.replace("\n", " ")
        safe_support = support_text.replace("\n", " ")
        events.append(
            f"Dialogue: 0,{start},{end},Primary,,0,0,0,,{tag_primary}{safe_primary}"
        )
        if safe_support:
            events.append(
                f"Dialogue: 1,{start},{end},Support,,0,0,0,,{tag_support}{safe_support}"
            )
    return "\n".join(head + events) + "\n"
